# Generated by Django 4.2.25 on 2025-10-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_table_tablereservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableReservation',
        ),
    ]
